In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Real estate.csv')
df.head(10)

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   
5   6             2012.667           7.1   
6   7             2012.667          34.5   
7   8             2013.417          20.3   
8   9             2013.500          31.7   
9  10             2013.417          17.9   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   
5                              2175.03000                                3   
6                               623.47310                                7   
7                               287.60250                                6   
8                              5512.03800                                1   
9                              1783.18000                                3   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1  
5     24.96305     121.51254                        32.1  
6     24.97933     121.53642                        40.3  
7     24.98042     121.54228                        46.7  
8     24.95095     121.48458                        18.8  
9     24.96731     121.51486                        22.1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   No                                      414 non-null    int64  
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64  
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [4]:
df.corr()['Y house price of unit area']

No                                       -0.028587
X1 transaction date                       0.087491
X2 house age                             -0.210567
X3 distance to the nearest MRT station   -0.673613
X4 number of convenience stores           0.571005
X5 latitude                               0.546307
X6 longitude                              0.523287
Y house price of unit area                1.000000
Name: Y house price of unit area, dtype: float64

In [5]:
df = df.drop(["No","X1 transaction date"], axis =1)
df

X2 house age  X3 distance to the nearest MRT station  \
0            32.0                                84.87882   
1            19.5                               306.59470   
2            13.3                               561.98450   
3            13.3                               561.98450   
4             5.0                               390.56840   
..            ...                                     ...   
409          13.7                              4082.01500   
410           5.6                                90.45606   
411          18.8                               390.96960   
412           8.1                               104.81010   
413           6.5                                90.45606   

     X4 number of convenience stores  X5 latitude  X6 longitude  \
0                                 10     24.98298     121.54024   
1                                  9     24.98034     121.53951   
2                                  5     24.98746     121.54391   
3                                  5     24.98746     121.54391   
4                                  5     24.97937     121.54245   
..                               ...          ...           ...   
409                                0     24.94155     121.50381   
410                                9     24.97433     121.54310   
411                                7     24.97923     121.53986   
412                                5     24.96674     121.54067   
413                                9     24.97433     121.54310   

     Y house price of unit area  
0                          37.9  
1                          42.2  
2                          47.3  
3                          54.8  
4                          43.1  
..                          ...  
409                        15.4  
410                        50.0  
411                        40.6  
412                        52.5  
413                        63.9  

[414 rows x 6 columns]

In [6]:
df_np = df.to_numpy()
df_np.shape

(414, 6)

In [7]:
X, y = df_np[:, :3], df_np[:, -1]
X.shape, y.shape

((414, 3), (414,))

In [8]:
from numpy.linalg import inv

def get_best_model(X, y):

    (n, p_minus_one) = X.shape
    p = p_minus_one + 1

    new_X = np.ones(shape=(n, p))
    new_X[:, 1:] = X

    return np.dot(np.dot(inv(np.dot(new_X.T, new_X)), new_X.T), y)

In [9]:
b = get_best_model(X,y)
b

array([ 4.29772862e+01, -2.52855827e-01, -5.37912962e-03,  1.29744248e+00])

In [22]:
def get_predictions(model, X):


    (n, p_minus_one) = X.shape
    p = p_minus_one + 1

    new_X = np.ones(shape=(n, p))
    new_X[:, 1:] = X

    return np.dot(new_X, model)

In [11]:
predictions = get_predictions(b,X)
predictions, predictions.shape

(array([47.40375034, 48.07436724, 43.07852862, 43.07852862, 46.0993014 ,
        33.37456896, 39.9821149 , 44.08191666,  6.60923209, 32.75153798,
        33.29565051, 52.57470191, 43.52959687, 29.72425667, 38.56354461,
        33.42958162, 49.18586792, 37.91190485, 47.10330967, 51.55432047,
        33.48952502, 47.90269176, 33.24138404, 48.00383409, 35.56823014,
        30.1600606 , 46.61579992, 45.34774298, 40.31347782, 45.24192333,
        12.11632193, 40.43613045, 32.06339697, 44.84883773, 47.0607081 ,
        17.518872  , 31.44652627, 33.92409478, 46.86915817, 43.81191859,
        17.58075915, 16.85460972, 37.54215143, 39.30535235, 44.61470775,
        41.47288038, 46.6715837 , 34.34547079, 12.08325432, 12.57896167,
        39.92301878, 26.9016475 , 31.01463869, 43.45374013, 43.83720418,
        28.71856653, 42.86387106, 50.87060583, 12.35139143, 44.29384237,
        32.40254428, 48.02505662, 30.81616899, 44.63999333, 33.19601187,
        42.55167827, 49.46776912, 46.75143695, 40.5

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mean_absolute_error(predictions,y ), mean_squared_error(y, predictions)

(6.485672172393673, 84.76070642266242)

In [13]:
n = 125
p = np.ones(4)
p[1:] = X[n]

p@b.T , df.loc[n]

(49.44248353474278,
 X2 house age                                1.10000
 X3 distance to the nearest MRT station    193.58450
 X4 number of convenience stores             6.00000
 X5 latitude                                24.96571
 X6 longitude                              121.54089
 Y house price of unit area                 48.60000
 Name: 125, dtype: float64)

# Substrating Mean

In [15]:
df

X2 house age  X3 distance to the nearest MRT station  \
0            32.0                                84.87882   
1            19.5                               306.59470   
2            13.3                               561.98450   
3            13.3                               561.98450   
4             5.0                               390.56840   
..            ...                                     ...   
409          13.7                              4082.01500   
410           5.6                                90.45606   
411          18.8                               390.96960   
412           8.1                               104.81010   
413           6.5                                90.45606   

     X4 number of convenience stores  X5 latitude  X6 longitude  \
0                                 10     24.98298     121.54024   
1                                  9     24.98034     121.53951   
2                                  5     24.98746     121.54391   
3                                  5     24.98746     121.54391   
4                                  5     24.97937     121.54245   
..                               ...          ...           ...   
409                                0     24.94155     121.50381   
410                                9     24.97433     121.54310   
411                                7     24.97923     121.53986   
412                                5     24.96674     121.54067   
413                                9     24.97433     121.54310   

     Y house price of unit area  
0                          37.9  
1                          42.2  
2                          47.3  
3                          54.8  
4                          43.1  
..                          ...  
409                        15.4  
410                        50.0  
411                        40.6  
412                        52.5  
413                        63.9  

[414 rows x 6 columns]

In [16]:
df = df - df.mean()

In [17]:
df

X2 house age  X3 distance to the nearest MRT station  \
0        14.28744                             -999.006869   
1         1.78744                             -777.290989   
2        -4.41256                             -521.901189   
3        -4.41256                             -521.901189   
4       -12.71256                             -693.317289   
..            ...                                     ...   
409      -4.01256                             2998.129311   
410     -12.11256                             -993.429629   
411       1.08744                             -692.916089   
412      -9.61256                             -979.075589   
413     -11.21256                             -993.429629   

     X4 number of convenience stores  X5 latitude  X6 longitude  \
0                           5.905797      0.01395      0.006879   
1                           4.905797      0.01131      0.006149   
2                           0.905797      0.01843      0.010549   
3                           0.905797      0.01843      0.010549   
4                           0.905797      0.01034      0.009089   
..                               ...          ...           ...   
409                        -4.094203     -0.02748     -0.029551   
410                         4.905797      0.00530      0.009739   
411                         2.905797      0.01020      0.006499   
412                         0.905797     -0.00229      0.007309   
413                         4.905797      0.00530      0.009739   

     Y house price of unit area  
0                     -0.080193  
1                      4.219807  
2                      9.319807  
3                     16.819807  
4                      5.119807  
..                          ...  
409                  -22.580193  
410                   12.019807  
411                    2.619807  
412                   14.519807  
413                   25.919807  

[414 rows x 6 columns]

In [18]:
df_np = df.to_numpy()
df_np.shape

(414, 6)

In [19]:
X, y = df_np[:, :3], df_np[:, -1]
X.shape, y.shape

((414, 3), (414,))

In [20]:
b = get_best_model(X,y)
b

array([ 2.35922393e-16, -2.52855827e-01, -5.37912962e-03,  1.29744248e+00])

In [23]:
predictions = get_predictions(b,X)
predictions, predictions.shape

(array([ 9.42355710e+00,  1.00941740e+01,  5.09833538e+00,  5.09833538e+00,
         8.11910817e+00, -4.60562428e+00,  2.00192166e+00,  6.10172342e+00,
        -3.13709612e+01, -5.22865526e+00, -4.68454272e+00,  1.45945087e+01,
         5.54940364e+00, -8.25593657e+00,  5.83351370e-01, -4.55061161e+00,
         1.12056747e+01, -6.82883824e-02,  9.12311643e+00,  1.35741272e+01,
        -4.49066821e+00,  9.92249852e+00, -4.73880919e+00,  1.00236409e+01,
        -2.41196310e+00, -7.82013263e+00,  8.63560668e+00,  7.36754975e+00,
         2.33328458e+00,  7.26173009e+00, -2.58638713e+01,  2.45593721e+00,
        -5.91679627e+00,  6.86864449e+00,  9.08051486e+00, -2.04613212e+01,
        -6.53366696e+00, -4.05609846e+00,  8.88896494e+00,  5.83172536e+00,
        -2.03994341e+01, -2.11255835e+01, -4.38041809e-01,  1.32515911e+00,
         6.63451451e+00,  3.49268715e+00,  8.69139046e+00, -3.63472245e+00,
        -2.58969389e+01, -2.54012316e+01,  1.94282554e+00, -1.10785457e+01,
        -6.9

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mean_absolute_error(predictions,y ), mean_squared_error(y, predictions)

(6.485672172393681, 84.76070642266242)

In [25]:
n = 125
p = np.ones(4)
p[1:] = X[n]

p@b.T , df.loc[n]

(11.462290298027517,
 X2 house age                              -16.612560
 X3 distance to the nearest MRT station   -890.301189
 X4 number of convenience stores             1.905797
 X5 latitude                                -0.003320
 X6 longitude                                0.007529
 Y house price of unit area                 10.619807
 Name: 125, dtype: float64)