In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [3]:
df.corr()['median_house_value']

longitude            -0.045967
latitude             -0.144160
housing_median_age    0.105623
total_rooms           0.134153
total_bedrooms        0.049686
population           -0.024650
households            0.065843
median_income         0.688075
median_house_value    1.000000
Name: median_house_value, dtype: float64

In [4]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [5]:
df = df.drop(['longitude', 'latitude','total_bedrooms','population','households','ocean_proximity'], axis = 1)
df

housing_median_age  total_rooms  median_income  median_house_value
0                    41.0        880.0         8.3252            452600.0
1                    21.0       7099.0         8.3014            358500.0
2                    52.0       1467.0         7.2574            352100.0
3                    52.0       1274.0         5.6431            341300.0
4                    52.0       1627.0         3.8462            342200.0
...                   ...          ...            ...                 ...
20635                25.0       1665.0         1.5603             78100.0
20636                18.0        697.0         2.5568             77100.0
20637                17.0       2254.0         1.7000             92300.0
20638                18.0       1860.0         1.8672             84700.0
20639                16.0       2785.0         2.3886             89400.0

[20640 rows x 4 columns]

In [7]:
df_np = df.to_numpy()
df_np.shape

(20640, 4)

In [8]:
X, y = df_np[:, :3], df_np[:, -1]
X.shape, y.shape

((20640, 3), (20640,))

In [9]:
X

array([[4.1000e+01, 8.8000e+02, 8.3252e+00],
       [2.1000e+01, 7.0990e+03, 8.3014e+00],
       [5.2000e+01, 1.4670e+03, 7.2574e+00],
       ...,
       [1.7000e+01, 2.2540e+03, 1.7000e+00],
       [1.8000e+01, 1.8600e+03, 1.8672e+00],
       [1.6000e+01, 2.7850e+03, 2.3886e+00]])

In [10]:
from numpy.linalg import inv

def get_best_model(X, y):

    (n, p_minus_one) = X.shape
    p = p_minus_one + 1

    new_X = np.ones(shape=(n, p))
    new_X[:, 1:] = X

    return np.dot(np.dot(inv(np.dot(new_X.T, new_X)), new_X.T), y)

In [11]:
b = get_best_model(X,y)
b

array([-2.43298794e+04,  1.97498062e+03,  3.88780381e+00,  4.24670389e+04])

In [12]:
def get_predictions(model, X):


    (n, p_minus_one) = X.shape
    p = p_minus_one + 1

    new_X = np.ones(shape=(n, p))
    new_X[:, 1:] = X

    return np.dot(new_X, model)

In [13]:
predictions = get_predictions(b,X)
predictions, predictions.shape

(array([413612.1853899 , 397280.10943459, 392272.80886442, ...,
         90201.8669527 ,  97745.54177132, 119534.11314304]),
 (20640,))

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mean_absolute_error(predictions,y ), mean_squared_error(y, predictions)

(60092.789096399414, 6475526461.788597)

In [ ]:
from numpy.linalg import inv

def get_best_model(X, y):
  '''
  Returns the model with the parameters that minimize the MSE.

  X: np.array of Floats with shape (n, p-1) of inputs
  y: np.array of Floats with shape (n,) of observed outputs

  Returns: np.array of shape (p,) representing the model.
  '''

  (n, p_minus_one) = X.shape
  p = p_minus_one + 1

  new_X = np.ones(shape=(n, p))
  new_X[:, 1:] = X

  return np.dot(np.dot(inv(np.dot(new_X.T, new_X)), new_X.T), y)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   housing_median_age  20640 non-null  float64
 1   total_rooms         20640 non-null  float64
 2   median_income       20640 non-null  float64
 3   median_house_value  20640 non-null  float64
dtypes: float64(4)
memory usage: 645.1 KB


In [7]:
df.mean()

housing_median_age        28.639486
total_rooms             2635.763081
median_income              3.870671
median_house_value    206855.816909
dtype: float64

In [8]:
# df = df - df.mean()

In [8]:
df

housing_median_age  total_rooms  median_income  median_house_value
0                    41.0        880.0         8.3252            452600.0
1                    21.0       7099.0         8.3014            358500.0
2                    52.0       1467.0         7.2574            352100.0
3                    52.0       1274.0         5.6431            341300.0
4                    52.0       1627.0         3.8462            342200.0
...                   ...          ...            ...                 ...
20635                25.0       1665.0         1.5603             78100.0
20636                18.0        697.0         2.5568             77100.0
20637                17.0       2254.0         1.7000             92300.0
20638                18.0       1860.0         1.8672             84700.0
20639                16.0       2785.0         2.3886             89400.0

[20640 rows x 4 columns]

In [10]:
df.mean()

housing_median_age        28.639486
total_rooms             2635.763081
median_income              3.870671
median_house_value    206855.816909
dtype: float64

In [9]:
y = df['median_house_value']
X = df.drop(['median_house_value'], axis=1)
X.shape
y.shape

(20640,)

In [10]:
X.shape

(20640, 3)

In [11]:
new_col = 1
X.insert(loc=0, column='New', value=new_col)
X.head(20)

New  housing_median_age  total_rooms  median_income
0     1                41.0        880.0         8.3252
1     1                21.0       7099.0         8.3014
2     1                52.0       1467.0         7.2574
3     1                52.0       1274.0         5.6431
4     1                52.0       1627.0         3.8462
5     1                52.0        919.0         4.0368
6     1                52.0       2535.0         3.6591
7     1                52.0       3104.0         3.1200
8     1                42.0       2555.0         2.0804
9     1                52.0       3549.0         3.6912
10    1                52.0       2202.0         3.2031
11    1                52.0       3503.0         3.2705
12    1                52.0       2491.0         3.0750
13    1                52.0        696.0         2.6736
14    1                52.0       2643.0         1.9167
15    1                50.0       1120.0         2.1250
16    1                52.0       1966.0         2.7750
17    1                52.0       1228.0         2.1202
18    1                50.0       2239.0         1.9911
19    1                52.0       1503.0         2.6033

In [12]:
X = X.to_numpy()
y = y.to_numpy()
X,y

(array([[1.0000e+00, 4.1000e+01, 8.8000e+02, 8.3252e+00],
        [1.0000e+00, 2.1000e+01, 7.0990e+03, 8.3014e+00],
        [1.0000e+00, 5.2000e+01, 1.4670e+03, 7.2574e+00],
        ...,
        [1.0000e+00, 1.7000e+01, 2.2540e+03, 1.7000e+00],
        [1.0000e+00, 1.8000e+01, 1.8600e+03, 1.8672e+00],
        [1.0000e+00, 1.6000e+01, 2.7850e+03, 2.3886e+00]]),
 array([452600., 358500., 352100., ...,  92300.,  84700.,  89400.]))

In [13]:
X.shape, y.shape

((20640, 4), (20640,))

In [14]:
b = np.linalg.inv(X.T @ X) @ X.T @ y
b

array([-2.43298794e+04,  1.97498062e+03,  3.88780381e+00,  4.24670389e+04])

In [15]:
predict = X[459]@b.T
predict,df.loc[459]

(130406.23380570544,
 housing_median_age        52.0000
 total_rooms              609.0000
 median_income              1.1696
 median_house_value    500001.0000
 Name: 459, dtype: float64)

In [21]:
predictions = X @ b.T
predictions

array([413612.1853899 , 397280.10943459, 392272.80886442, ...,
        90201.8669527 ,  97745.54177132, 119534.11314304])

In [22]:
predictions.shape

(20640,)

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mean_absolute_error(predictions, y), mean_squared_error(predictions, y)

(60092.789096399414, 6475526461.788596)

In [24]:
from numpy.linalg import inv

def get_best_model(X, y):
  '''
  Returns the model with the parameters that minimize the MSE.

  X: np.array of Floats with shape (n, p-1) of inputs
  y: np.array of Floats with shape (n,) of observed outputs

  Returns: np.array of shape (p,) representing the model.
  '''

  (n, p_minus_one) = X.shape
  p = p_minus_one + 1

  new_X = np.ones(shape=(n, p))
  new_X[:, 1:] = X

  return np.dot(np.dot(inv(np.dot(new_X.T, new_X)), new_X.T), y)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
