In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('kc_house_data.csv')
df.head(10)

id             date      price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900.0         3       1.00         1180   
1  6414100192  20141209T000000   538000.0         3       2.25         2570   
2  5631500400  20150225T000000   180000.0         2       1.00          770   
3  2487200875  20141209T000000   604000.0         4       3.00         1960   
4  1954400510  20150218T000000   510000.0         3       2.00         1680   
5  7237550310  20140512T000000  1225000.0         4       4.50         5420   
6  1321400060  20140627T000000   257500.0         3       2.25         1715   
7  2008000270  20150115T000000   291850.0         3       1.50         1060   
8  2414600126  20150415T000000   229500.0         3       1.00         1780   
9  3793500160  20150312T000000   323000.0         3       2.50         1890   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   
5    101930     1.0           0     0  ...     11        3890           1530   
6      6819     2.0           0     0  ...      7        1715              0   
7      9711     1.0           0     0  ...      7        1060              0   
8      7470     1.0           0     0  ...      7        1050            730   
9      6560     2.0           0     0  ...      7        1890              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   
5      2001             0    98053  47.6561 -122.005           4760   
6      1995             0    98003  47.3097 -122.327           2238   
7      1963             0    98198  47.4095 -122.315           1650   
8      1960             0    98146  47.5123 -122.337           1780   
9      2003             0    98038  47.3684 -122.031           2390   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  
5      101930  
6        6819  
7        9711  
8        8113  
9        7570  

[10 rows x 21 columns]

In [3]:
y = df['price']
y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [4]:
X = df.drop(columns='price')

In [5]:
X

id             date  bedrooms  bathrooms  sqft_living  \
0      7129300520  20141013T000000         3       1.00         1180   
1      6414100192  20141209T000000         3       2.25         2570   
2      5631500400  20150225T000000         2       1.00          770   
3      2487200875  20141209T000000         4       3.00         1960   
4      1954400510  20150218T000000         3       2.00         1680   
...           ...              ...       ...        ...          ...   
21608   263000018  20140521T000000         3       2.50         1530   
21609  6600060120  20150223T000000         4       2.50         2310   
21610  1523300141  20140623T000000         2       0.75         1020   
21611   291310100  20150116T000000         3       2.50         1600   
21612  1523300157  20141015T000000         2       0.75         1020   

       sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
0          5650     1.0           0     0          3      7        1180   
1          7242     2.0           0     0          3      7        2170   
2         10000     1.0           0     0          3      6         770   
3          5000     1.0           0     0          5      7        1050   
4          8080     1.0           0     0          3      8        1680   
...         ...     ...         ...   ...        ...    ...         ...   
21608      1131     3.0           0     0          3      8        1530   
21609      5813     2.0           0     0          3      8        2310   
21610      1350     2.0           0     0          3      7        1020   
21611      2388     2.0           0     0          3      8        1600   
21612      1076     2.0           0     0          3      7        1020   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0                  0      1955             0    98178  47.5112 -122.257   
1                400      1951          1991    98125  47.7210 -122.319   
2                  0      1933             0    98028  47.7379 -122.233   
3                910      1965             0    98136  47.5208 -122.393   
4                  0      1987             0    98074  47.6168 -122.045   
...              ...       ...           ...      ...      ...      ...   
21608              0      2009             0    98103  47.6993 -122.346   
21609              0      2014             0    98146  47.5107 -122.362   
21610              0      2009             0    98144  47.5944 -122.299   
21611              0      2004             0    98027  47.5345 -122.069   
21612              0      2008             0    98144  47.5941 -122.299   

       sqft_living15  sqft_lot15  
0               1340        5650  
1               1690        7639  
2               2720        8062  
3               1360        5000  
4               1800        7503  
...              ...         ...  
21608           1530        1509  
21609           1830        7200  
21610           1020        2007  
21611           1410        1287  
21612           1020        1357  

[21613 rows x 20 columns]

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   bedrooms       21613 non-null  int64  
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64  
 5   sqft_lot       21613 non-null  int64  
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64  
 8   view           21613 non-null  int64  
 9   condition      21613 non-null  int64  
 10  grade          21613 non-null  int64  
 11  sqft_above     21613 non-null  int64  
 12  sqft_basement  21613 non-null  int64  
 13  yr_built       21613 non-null  int64  
 14  yr_renovated   21613 non-null  int64  
 15  zipcode        21613 non-null  int64  
 16  lat            21613 non-null  float64
 17  long           21613 non-null  float64
 18  sqft_l

In [7]:
X = df.to_numpy()
X

array([[7129300520, '20141013T000000', 221900.0, ..., -122.257, 1340,
        5650],
       [6414100192, '20141209T000000', 538000.0, ..., -122.319, 1690,
        7639],
       [5631500400, '20150225T000000', 180000.0, ..., -122.233, 2720,
        8062],
       ...,
       [1523300141, '20140623T000000', 402101.0, ..., -122.299, 1020,
        2007],
       [291310100, '20150116T000000', 400000.0, ..., -122.069, 1410,
        1287],
       [1523300157, '20141015T000000', 325000.0, ..., -122.299, 1020,
        1357]], dtype=object)

In [8]:
X.shape

(21613, 21)

In [9]:
y = y.to_numpy()

In [10]:
y.shape

(21613,)

<h1>OLS Regression in Matrix Form</h1>

$y = Xb+e$</b>

$ e = y - Xb$

$\sum e_i^{2} = e'e$

$e'e = (y-Xb)'(y-Xb)$
$    = y'y - 2b'X'y+b'X'Xb$<br>

$\frac{\partial e'e}{\partial b} = -2X'y + 2X'Xb=0$<br>

$\therefore (X'X)b=X'y$ <br>

$\therefore b = (X'X)^{-1}X'y$

In [11]:
#b = np.linalg.inv(X.T @ X) @ X.T @ y

###  In this Method Size of data Matter(Dead Kernel)

# Trying With New Data Sets

In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('Real estate.csv')
df.head(10)

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   
5   6             2012.667           7.1   
6   7             2012.667          34.5   
7   8             2013.417          20.3   
8   9             2013.500          31.7   
9  10             2013.417          17.9   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   
5                              2175.03000                                3   
6                               623.47310                                7   
7                               287.60250                                6   
8                              5512.03800                                1   
9                              1783.18000                                3   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1  
5     24.96305     121.51254                        32.1  
6     24.97933     121.53642                        40.3  
7     24.98042     121.54228                        46.7  
8     24.95095     121.48458                        18.8  
9     24.96731     121.51486                        22.1

In [14]:
df=df.drop(columns='No')

In [15]:
df.mean()

X1 transaction date                       2013.148971
X2 house age                                17.712560
X3 distance to the nearest MRT station    1083.885689
X4 number of convenience stores              4.094203
X5 latitude                                 24.969030
X6 longitude                               121.533361
Y house price of unit area                  37.980193
dtype: float64

In [16]:
df = df - df.mean()

In [17]:
df.mean()

X1 transaction date                       1.043502e-13
X2 house age                             -9.267949e-16
X3 distance to the nearest MRT station   -1.362045e-13
X4 number of convenience stores           4.290717e-18
X5 latitude                               1.664798e-15
X6 longitude                             -2.474886e-14
Y house price of unit area                1.270052e-15
dtype: float64

In [18]:
new_col = 1
df.insert(loc=0, column='New', value=new_col)
df.head(20)


New  X1 transaction date  X2 house age  \
0     1            -0.231971      14.28744   
1     1            -0.231971       1.78744   
2     1             0.434029      -4.41256   
3     1             0.351029      -4.41256   
4     1            -0.315971     -12.71256   
5     1            -0.481971     -10.61256   
6     1            -0.481971      16.78744   
7     1             0.268029       2.58744   
8     1             0.351029      13.98744   
9     1             0.268029       0.18744   
10    1            -0.065971      17.08744   
11    1             0.184029     -11.41256   
12    1            -0.231971      -4.71256   
13    1            -0.481971       2.68744   
14    1             0.351029      -4.51256   
15    1             0.434029      17.98744   
16    1             0.101029     -17.71256   
17    1            -0.398971      -0.01256   
18    1             0.268029      -0.81256   
19    1            -0.481971     -16.21256   

    X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                              -999.006869                         5.905797   
1                              -777.290989                         4.905797   
2                              -521.901189                         0.905797   
3                              -521.901189                         0.905797   
4                              -693.317289                         0.905797   
5                              1091.144311                        -1.094203   
6                              -460.412589                         2.905797   
7                              -796.283189                         1.905797   
8                              4428.152311                        -3.094203   
9                               699.294311                        -1.094203   
10                             -678.672289                        -3.094203   
11                             -993.429629                         4.905797   
12                             -591.654389                         0.905797   
13                             1385.759311                        -0.094203   
14                               80.952311                        -0.094203   
15                             -504.677389                        -2.094203   
16                             -790.887889                         1.905797   
17                             -733.034189                        -3.094203   
18                             -715.749389                         3.905797   
19                            -1060.502849                         2.905797   

    X5 latitude  X6 longitude  Y house price of unit area  
0       0.01395      0.006879                   -0.080193  
1       0.01131      0.006149                    4.219807  
2       0.01843      0.010549                    9.319807  
3       0.01843      0.010549                   16.819807  
4       0.01034      0.009089                    5.119807  
5      -0.00598     -0.020821                   -5.880193  
6       0.01030      0.003059                    2.319807  
7       0.01139      0.008919                    8.719807  
8      -0.01808     -0.048781                  -19.180193  
9      -0.00172     -0.018501                  -15.880193  
10      0.00446      0.000359                    3.419807  
11      0.00530      0.009739                   20.119807  
12     -0.00388      0.004009                    1.319807  
13     -0.00795     -0.022901                  -14.180193  
14      0.02253      0.000699                   -3.680193  
15      0.01337      0.012829                   12.519807  
16      0.00841      0.011219                   32.119807  
17      0.00641     -0.002171                   -0.580193  
18     -0.00153      0.011149                    4.319807  
19     -0.00131      0.007659                    9.719807

In [19]:
y = df['Y house price of unit area']

In [20]:
y

0      -0.080193
1       4.219807
2       9.319807
3      16.819807
4       5.119807
         ...    
409   -22.580193
410    12.019807
411     2.619807
412    14.519807
413    25.919807
Name: Y house price of unit area, Length: 414, dtype: float64

In [21]:
y = y.to_numpy()

In [22]:
y.shape

(414,)

In [23]:
y.T

array([ -0.08019324,   4.21980676,   9.31980676,  16.81980676,
         5.11980676,  -5.88019324,   2.31980676,   8.71980676,
       -19.18019324, -15.88019324,   3.41980676,  20.11980676,
         1.31980676, -14.18019324,  -3.68019324,  12.51980676,
        32.11980676,  -0.58019324,   4.31980676,   9.71980676,
        -8.68019324,  13.61980676, -13.38019324,   9.91980676,
         0.81980676, -10.98019324,  18.21980676,  -4.38019324,
         9.01980676,  19.11980676, -15.88019324, -12.98019324,
        -3.78019324,  11.31980676,  17.11980676, -10.68019324,
       -15.08019324, -12.68019324,   9.71980676,   8.21980676,
       -22.08019324, -19.78019324,  -3.28019324,  -3.88019324,
        15.91980676,   0.31980676,   4.01980676,  23.51980676,
       -24.58019324, -24.78019324,   6.21980676, -17.28019324,
       -10.98019324,   0.91980676,  13.71980676, -24.28019324,
         3.91980676,  15.51980676, -15.38019324,   4.41980676,
       -16.68019324,  25.21980676, -10.28019324,  17.01

In [24]:
X = df.drop(columns='Y house price of unit area')

In [25]:
X = X.to_numpy()

In [26]:
X.shape

(414, 7)

In [27]:
b = np.linalg.inv(X.T @ X) @ X.T @ y

In [28]:
b

array([-1.21916366e-12,  5.14622746e+00, -2.69695448e-01, -4.48746107e-03,
        1.13327690e+00,  2.25472976e+02, -1.24236012e+01])

In [29]:
predict = X[44]@b.T
predict

9.69014169678615

In [30]:
df.loc[44]

New                                         1.000000
X1 transaction date                         0.434029
X2 house age                              -15.012560
X3 distance to the nearest MRT station   -550.409489
X4 number of convenience stores            -0.094203
X5 latitude                                 0.005420
X6 longitude                                0.014289
Y house price of unit area                 15.919807
Name: 44, dtype: float64

# Testing With Dummy Data

In [44]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_excel('mlr07.xls', engine='xlrd')
df.head(10)

*** No CODEPAGE record, no encoding_override: will use 'iso-8859-1'


X1   X2    X3    X4   X5
0   8.0   78   284   9.1  109
1   9.3   68   433   8.7  144
2   7.5   70   739   7.2  113
3   8.9   96  1792   8.9   97
4  10.2   74   477   8.3  206
5   8.3  111   362  10.9  124
6   8.8   77   671  10.0  152
7   8.8  168   636   9.1  162
8  10.7   82   329   8.7  150
9  11.7   89   634   7.6  134

In [46]:
df = df - df.mean()

In [47]:
df

X1         X2           X3        X4          X5
0  -1.305660  -38.09434  -305.792453 -0.335849   -1.641509
1  -0.005660  -48.09434  -156.792453 -0.735849   33.358491
2  -1.805660  -46.09434   149.207547 -2.235849    2.358491
3  -0.405661  -20.09434  1202.207547 -0.535849  -13.641509
4   0.894339  -42.09434  -112.792453 -1.135849   95.358491
5  -1.005660   -5.09434  -227.792453  1.464151   13.358491
6  -0.505660  -39.09434    81.207547  0.564151   41.358491
7  -0.505660   51.90566    46.207547 -0.335849   51.358491
8   1.394339  -34.09434  -260.792453 -0.735849   39.358491
9   2.394339  -27.09434    44.207547 -1.835849   23.358491
10 -0.805660   32.90566    41.207547  1.364151  181.358491
11 -1.005660  -56.09434  -332.792453  0.064151   -2.641509
12 -1.105661  -20.09434  -305.792453 -0.635849    0.358491
13 -1.405660  -33.09434    13.207547  0.064151   71.358491
14  0.994340   13.90566    96.207547 -0.735849   18.358491
15 -1.905660   28.90566  -244.792453  1.764151   47.358491
16  0.294340   -4.09434   767.207547  0.264151   75.358491
17 -0.005660   14.90566   -45.792453  0.164151   66.358491
18  1.294340  -36.09434  -384.792453 -0.335849   16.358491
19  0.394339   13.90566   674.207547 -0.235849   68.358491
20  2.294340   23.90566    98.207547 -1.135849  -30.641509
21 -1.205660   37.90566  -235.792453 -1.035849   -7.641509
22  0.494340    1.90566  1042.207547 -0.035849   -9.641509
23 -1.905660  -22.09434  -241.792453  0.364151    6.358491
24  0.094339    2.90566  -219.792453  0.964151  -22.641509
25  1.894339   36.90566    58.207547  0.464151  -32.641509
26 -0.205660   -0.09434  -223.792453 -0.235849   -8.641509
27  1.194340  -19.09434   -49.792453  0.864151  -15.641509
28  2.594339   59.90566    90.207547 -0.535849  -30.641509
29 -0.905661  -41.09434  -244.792453  0.164151  -18.641509
30 -4.305660   17.90566   -64.792453  0.864151   15.358491
31  0.494340   44.90566   280.207547  0.964151   -2.641509
32  0.494340   -5.09434    79.207547  0.264151  -33.641509
33  1.494340   -2.09434  -137.792453  0.164151  -50.641509
34  0.794340   25.90566  -159.792453  1.264151  -39.641509
35  1.594339  121.90566   232.207547  0.864151  -24.641509
36 -0.105661  -38.09434  -399.792453  1.264151  -17.641509
37 -1.005660   79.90566   277.207547  0.164151   -4.641509
38 -2.005660    8.90566   379.207547  1.064151   51.358491
39  0.094339  -34.09434   -90.792453 -1.735849  -15.641509
40  0.094339    8.90566   335.207547  0.764151  -19.641509
41  0.494340   12.90566  -236.792453  0.464151  -58.641509
42 -5.705661  -32.09434  -301.792453 -1.035849   -0.641509
43 -0.905661   66.90566   128.207547  0.964151  -41.641509
44  1.494340    2.90566   -49.792453 -0.235849  -53.641509
45  0.794340   63.90566    78.207547  3.564151   -4.641509
46 -0.305660  -34.09434  -242.792453 -0.635849  -70.641509
47  0.694340  -45.09434  -244.792453 -0.235849  -60.641509
48  1.994340    1.90566  -126.792453 -1.635849  -75.641509
49  1.994340    4.90566   138.207547 -1.235849  -24.641509
50  3.494340  -48.09434  -206.792453 -2.035849  -53.641509
51  0.694340   -4.09434  -273.792453  0.964151  -53.641509
52 -2.605661   -7.09434  -201.792453 -0.535849  -16.641509

In [48]:
y = df['X1']
y.head(10)

0   -1.305660
1   -0.005660
2   -1.805660
3   -0.405661
4    0.894339
5   -1.005660
6   -0.505660
7   -0.505660
8    1.394339
9    2.394339
Name: X1, dtype: float64

In [49]:
X = df.drop(columns='X1')
X.head(10)

X2           X3        X4         X5
0 -38.09434  -305.792453 -0.335849  -1.641509
1 -48.09434  -156.792453 -0.735849  33.358491
2 -46.09434   149.207547 -2.235849   2.358491
3 -20.09434  1202.207547 -0.535849 -13.641509
4 -42.09434  -112.792453 -1.135849  95.358491
5  -5.09434  -227.792453  1.464151  13.358491
6 -39.09434    81.207547  0.564151  41.358491
7  51.90566    46.207547 -0.335849  51.358491
8 -34.09434  -260.792453 -0.735849  39.358491
9 -27.09434    44.207547 -1.835849  23.358491

In [50]:
new_col = 1
X.insert(loc=0, column='New', value=new_col)
X.head(20)


New        X2           X3        X4          X5
0     1 -38.09434  -305.792453 -0.335849   -1.641509
1     1 -48.09434  -156.792453 -0.735849   33.358491
2     1 -46.09434   149.207547 -2.235849    2.358491
3     1 -20.09434  1202.207547 -0.535849  -13.641509
4     1 -42.09434  -112.792453 -1.135849   95.358491
5     1  -5.09434  -227.792453  1.464151   13.358491
6     1 -39.09434    81.207547  0.564151   41.358491
7     1  51.90566    46.207547 -0.335849   51.358491
8     1 -34.09434  -260.792453 -0.735849   39.358491
9     1 -27.09434    44.207547 -1.835849   23.358491
10    1  32.90566    41.207547  1.364151  181.358491
11    1 -56.09434  -332.792453  0.064151   -2.641509
12    1 -20.09434  -305.792453 -0.635849    0.358491
13    1 -33.09434    13.207547  0.064151   71.358491
14    1  13.90566    96.207547 -0.735849   18.358491
15    1  28.90566  -244.792453  1.764151   47.358491
16    1  -4.09434   767.207547  0.264151   75.358491
17    1  14.90566   -45.792453  0.164151   66.358491
18    1 -36.09434  -384.792453 -0.335849   16.358491
19    1  13.90566   674.207547 -0.235849   68.358491

In [51]:
y = y.to_numpy()
y

array([-1.30566041e+00, -5.66021872e-03, -1.80566041e+00, -4.05660791e-01,
        8.94339400e-01, -1.00566022e+00, -5.05660219e-01, -5.05660219e-01,
        1.39433940e+00,  2.39433940e+00, -8.05660410e-01, -1.00566022e+00,
       -1.10566060e+00, -1.40566031e+00,  9.94339780e-01, -1.90566031e+00,
        2.94339971e-01, -5.66021872e-03,  1.29433997e+00,  3.94339399e-01,
        2.29433997e+00, -1.20566003e+00,  4.94339781e-01, -1.90566031e+00,
        9.43392093e-02,  1.89433940e+00, -2.05660029e-01,  1.19433959e+00,
        2.59433921e+00, -9.05660791e-01, -4.30566041e+00,  4.94339781e-01,
        4.94339781e-01,  1.49433978e+00,  7.94339970e-01,  1.59433921e+00,
       -1.05660601e-01, -1.00566022e+00, -2.00566022e+00,  9.43392093e-02,
        9.43392093e-02,  4.94339781e-01, -5.70566050e+00, -9.05660791e-01,
        1.49433978e+00,  7.94339970e-01, -3.05660410e-01,  6.94339590e-01,
        1.99433978e+00,  1.99433978e+00,  3.49433978e+00,  6.94339590e-01,
       -2.60566060e+00])

In [52]:
X = X.to_numpy()

In [53]:
X

array([[ 1.00000000e+00, -3.80943396e+01, -3.05792453e+02,
        -3.35848611e-01, -1.64150943e+00],
       [ 1.00000000e+00, -4.80943396e+01, -1.56792453e+02,
        -7.35849183e-01,  3.33584906e+01],
       [ 1.00000000e+00, -4.60943396e+01,  1.49207547e+02,
        -2.23584918e+00,  2.35849057e+00],
       [ 1.00000000e+00, -2.00943396e+01,  1.20220755e+03,
        -5.35849373e-01, -1.36415094e+01],
       [ 1.00000000e+00, -4.20943396e+01, -1.12792453e+02,
        -1.13584880e+00,  9.53584906e+01],
       [ 1.00000000e+00, -5.09433962e+00, -2.27792453e+02,
         1.46415063e+00,  1.33584906e+01],
       [ 1.00000000e+00, -3.90943396e+01,  8.12075472e+01,
         5.64151008e-01,  4.13584906e+01],
       [ 1.00000000e+00,  5.19056604e+01,  4.62075472e+01,
        -3.35848611e-01,  5.13584906e+01],
       [ 1.00000000e+00, -3.40943396e+01, -2.60792453e+02,
        -7.35849183e-01,  3.93584906e+01],
       [ 1.00000000e+00, -2.70943396e+01,  4.42075472e+01,
        -1.83584909e+00

In [54]:
b = np.linalg.inv(X.T @ X) @ X.T @ y
b

array([-4.39051160e-16,  7.39161503e-03,  5.83715656e-04, -3.30230237e-01,
       -9.46288488e-03])

In [55]:
predict = X[44]@b.T
predict

0.5779008484531195

In [56]:
df.loc[44]

X1     1.494340
X2     2.905660
X3   -49.792453
X4    -0.235849
X5   -53.641509
Name: 44, dtype: float64